### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by iamglicious** [laravel/cashier-mollie#321] opened 2021-05-28 10:29 UTC
Hoi Sander,

We are facing some issues with the config. We have all enabled paypal, ideal and creditcard. 
But the only what it is accepting is creditcard. We have put NULL but it only returns creditcard.

If we do it like the example. We get server 500 error

 /**
         * A comma-separated list of allowed Mollie payment methods for the first payment. Make sure the methods are
         * enabled in the Mollie dashboard. Set to NULL to let Mollie handle this for you. Can be overridden per plan.
         * @example 'ideal,creditcard'
         */
        'method' => NULL,

**Comment by sandervanhooft** [comment] 2021-05-28 11:13
What version are you using?

**Comment by iamglicious** [comment] 2021-05-28 11:56
> What version are you using?

Latest version. But think we found it. SEPA need to be on before we can use ideal in the subscriptions..

**Comment by sandervanhooft** [comment] 2021-05-28 12:43
Yes that would make sense 😅. iDEAL payments result in SEPA mandates. So this is not a bug.

Closing this for now, let me know if it should be reopened.

**Closed by sandervanhooft** 2021-05-28 12:43 UTC
