### ISSUE TITLE
What does cashier:run do exactly and how should I use it?

### ISSUE THREAD

**Issue by zqstack** [laravel/cashier-mollie#156] opened 2020-02-20 19:45 UTC
Dear Developers,

How should I use `cashier:run`? When I run it multiple times from the command line before it should be processed and afterwards, it creates a new (not paid) order every time and increases the `cycle_started_at`.

Am I misunderstanding how it works? I thought I would be able to run `cashien:run` anytime and it wouldn't do anything whenthere were no processable items? I have added some screenshots from my database and command line.

![subscriptions](https://user-images.githubusercontent.com/60988202/74971518-88db9500-5420-11ea-954b-260b68e1e83e.png)
![order_items](https://user-images.githubusercontent.com/60988202/74971513-8711d180-5420-11ea-92a0-682151f0d40f.png)
![orders](https://user-images.githubusercontent.com/60988202/74971517-8842fe80-5420-11ea-991f-b855c7ee77db.png)
![command_line](https://user-images.githubusercontent.com/60988202/74972092-6eee8200-5421-11ea-9fc5-fb5366ee5a9c.png)

Thank you for your time!

Sincerely,

zqstack

**Comment by zqstack** [comment] 2020-02-20 20:19
Or does this happen because I am using test mode and all subscription payments are `open` except for the first one which is `paid`?

**Comment by sandervanhooft** [comment] 2020-02-23 17:35
I haven't seen this issue before.

1. Are you overriding the Carbon datetime in any way? Can there be another reason for abnormal  clock behaviour?
2. Did you do any customisations?
3. Can you share your `cashier` and `cashier_plans` config?

**Comment by zqstack** [comment] 2020-02-24 17:44
1. It might be because I've temporarily set the plan interval to 5 minutes?
2. I've added a migration to set owner_type's to nullable to prevent an error
3. Please find them, and the migration, attached

[cashier.php.txt](https://github.com/laravel/cashier-mollie/files/4245941/cashier.php.txt)
[cashier_plans.php.txt](https://github.com/laravel/cashier-mollie/files/4245942/cashier_plans.php.txt)
[2020_02_12_191006_set_cashier_owner_types_to_nullable.php.txt](https://github.com/laravel/cashier-mollie/files/4245944/2020_02_12_191006_set_cashier_owner_types_to_nullable.php.txt)

**Comment by sandervanhooft** [comment] 2020-02-25 14:58
> 2. I've added a migration to set owner_type's to nullable to prevent an error

Can you elaborate on this? I suspect this is breaking cashier:run in your case, because the morphMany requires the `owner_type` to resolve and update the items.

**Comment by zqstack** [comment] 2020-02-25 21:03
I don't recall why I did that, but unfortunately I've received some errors while setting up and this way I resolved the error. However, in my database, all data in all owner_type fields are currently filled with "App\User", so NULL values are actually not used.

Do you have an idea perhaps?

Thank you for your time!

**Comment by sandervanhooft** [comment] 2020-02-26 11:30
@zqstack I've just tested the `5 mins` interval and can confirm this is causing the issue.

In real life, I don't expect this to cause issues, but this may be the cause:

https://github.com/laravel/cashier-mollie/blob/ed8bfa74b3a9c63f8e06bc9b9cdf2e8bbdb3f714/src/Order/OrderItem.php#L41-L43

**Comment by sandervanhooft** [comment] 2020-02-26 11:59
Found it, fixing it.

**Comment by sandervanhooft** [comment] 2020-02-26 12:20
Merged, will be included in the upcoming release. Thanks for the detailed report @zqstack .

**Closed** 2020-02-26 12:19 UTC
