### ISSUE TITLE
Update Payment Method

### ISSUE THREAD

**Issue by blankflo** [laravel/cashier-mollie#281] opened 2020-12-08 13:39 UTC
Hi , i am newbie for that package but i enjoy it , and for my project i need to update payment method .
One of the issue speak about that but i'am not completely understand .
Can someone help me to do it pls ?
It will be vey nice , thank you in advance !

**Comment by sandervanhooft** [comment] 2020-12-09 12:34
Duplicate of #205

**Closed by sandervanhooft** 2020-12-09 12:34 UTC
