### ISSUE TITLE
Recurrent payment

### ISSUE THREAD

**Issue by gabzon** [laravel/cashier-mollie#328] opened 2021-07-05 12:42 UTC
Hi, 
I am having problems with the recurrent payments, they are not being executed. First payment works fine, but after nothing happens when the cycle ends. 
In my config/cashier_plans.php I have change the intervals to 1 day for testing. Is there any way I could test recurrent payments with Mollie?

`
'plans' => [
    'monthly' => [
        'amount' => [
            'value' => '1.00',
            'currency' => 'EUR',
        ],
        'interval' => '1 day',    
        'description' => 'Monthly payment',
    ]
]
`
I also run the schedule for cashier:run

Am I missing something? do I need to configure something else. 
Thanks for the help

**Comment by sandervanhooft** [comment] 2021-07-05 13:26
Hi,

Can you check the following?

- your Laravel logs
- the events for the payments in the Mollie dashboard at mollie.com. If you look up the payment, on desktop the events will be in the far column.
- running cashier:run manually

**Comment by gabzon** [comment] 2021-07-06 12:01
Ok I think is has something to do with the scheduler

Here is my log
<img width="1709" alt="Screenshot 2021-07-06 at 13 54 16" src="https://user-images.githubusercontent.com/142036/124595834-cb5d1080-de61-11eb-9e76-fe05b0cf3a65.png">

I have an error when I run cashier:run
<img width="1133" alt="Screenshot 2021-07-06 at 13 48 00" src="https://user-images.githubusercontent.com/142036/124595931-eb8ccf80-de61-11eb-9db9-49626a55018e.png">

I went to the mollie dashboard. I didn't see any events, only the one for the first payment. all others were never called. 

I have added this line of code in my "app/console/kernel.php" as instructed:
`$schedule->command('cashier:run')->daily()->withoutOverlapping(); `

am I missing something? Do I need to do something else?

**Comment by sandervanhooft** [comment] 2021-07-07 12:50
Can you check in the database what order items are due to be processed, and how the owner is defined for each order item?

**Comment by sandervanhooft** [comment] 2021-07-07 13:06
Also, can you run this and share the output here:

```php
dd(OrderItem::shouldProcess()->get()->owners);
```

**Comment by gabzon** [comment] 2021-07-07 13:40
Yes sure, 
Where exactly should I run this ? Where do I copy this code?

**Comment by sandervanhooft** [comment] 2021-07-07 13:44
Anywhere :).

You can use artisan tinker, run it from a controller, route, etc. As long as you can see the output.

**Comment by gabzon** [comment] 2021-07-08 12:18
I used tinker, I guess is the most straightforward and I get this message. 


<img width="696" alt="Screenshot 2021-07-08 at 14 15 52" src="https://user-images.githubusercontent.com/142036/124919910-0cd2f480-dff7-11eb-950a-11f8342f8c47.png">

Do you have any ideas?
Thank you very much for your help

**Comment by sandervanhooft** [comment] 2021-07-09 10:57
Try something like this:

```php
dd(Laravel\Cashier\Order\OrderItem::shouldProcess()->get()->owners());
```

**Comment by gabzon** [comment] 2021-07-13 10:43
This is the result I get.  Could you figure out what the problem could be? 

`Psy Shell v0.10.6 (PHP 7.3.29-1+0~20210701.86+debian9~1.gbp7ad6eb — cli) by Justin Hileman
>>> dd(Laravel\Cashier\Order\OrderItem::shouldProcess()->get()->owners());
Illuminate\Support\Collection^ {#4648
  #items: array:10 [
    0 => null
    1 => App\Models\User^ {#4638
      #fillable: array:8 [
        0 => "name"
        1 => "email"
        2 => "password"
        3 => "birthday"
        4 => "bio"
        5 => "gender"
        6 => "phone"
        7 => "role"
      ]
      #hidden: array:4 [
        0 => "password"
        1 => "remember_token"
        2 => "two_factor_recovery_codes"
        3 => "two_factor_secret"
      ]
      #casts: array:1 [
        "email_verified_at" => "datetime"
      ]
      #appends: array:1 [
        0 => "profile_photo_url"
      ]
      #connection: "mysql"
      #table: "users"
      #primaryKey: "id"
      #keyType: "int"
      +incrementing: true
      #with: []
      #withCount: []
      #perPage: 15
      +exists: true
      +wasRecentlyCreated: false
      #attributes: array:22 [
        "id" => 22
        "name" => "Kouamé Kouadio"
        "email" => "kouame@dancefloorgenevasalsa.ch"
        "email_verified_at" => "2021-05-04 13:24:55"
        "password" => "$2y$10$SGq5u0hHHhFzrUKI7YsUmOaybMO9mOYZEA7h2eDlOOmZ.LKWwU0xe"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => "iHV9YL82FNQ5RqQnjWVGWiFzAwBaMXFiacXlEpdtA0HYLnByC5tmo2044iu0"
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "admin"
        "mollie_customer_id" => "cst_WfkdbwqDWK"
        "mollie_mandate_id" => "mdt_tKxujBjTgw"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-05-04 13:24:21"
        "updated_at" => "2021-05-24 14:35:49"
      ]
      #original: array:22 [
        "id" => 22
        "name" => "Kouamé Kouadio"
        "email" => "kouame@dancefloorgenevasalsa.ch"
        "email_verified_at" => "2021-05-04 13:24:55"
        "password" => "$2y$10$SGq5u0hHHhFzrUKI7YsUmOaybMO9mOYZEA7h2eDlOOmZ.LKWwU0xe"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => "iHV9YL82FNQ5RqQnjWVGWiFzAwBaMXFiacXlEpdtA0HYLnByC5tmo2044iu0"
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "admin"
        "mollie_customer_id" => "cst_WfkdbwqDWK"
        "mollie_mandate_id" => "mdt_tKxujBjTgw"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-05-04 13:24:21"
        "updated_at" => "2021-05-24 14:35:49"
      ]
      #changes: []
      #classCastCache: []
      #dates: []
      #dateFormat: null
      #dispatchesEvents: []
      #observables: []
      #relations: []
      #touches: []
      +timestamps: true
      #visible: []
      #guarded: array:1 [
        0 => "*"
      ]
      #rememberTokenName: "remember_token"
      #accessToken: null
    }
    2 => App\Models\User^ {#4640
      #fillable: array:8 [
        0 => "name"
        1 => "email"
        2 => "password"
        3 => "birthday"
        4 => "bio"
        5 => "gender"
        6 => "phone"
        7 => "role"
      ]
      #hidden: array:4 [
        0 => "password"
        1 => "remember_token"
        2 => "two_factor_recovery_codes"
        3 => "two_factor_secret"
      ]
      #casts: array:1 [
        "email_verified_at" => "datetime"
      ]
      #appends: array:1 [
        0 => "profile_photo_url"
      ]
      #connection: "mysql"
      #table: "users"
      #primaryKey: "id"
      #keyType: "int"
      +incrementing: true
      #with: []
      #withCount: []
      #perPage: 15
      +exists: true
      +wasRecentlyCreated: false
      #attributes: array:22 [
        "id" => 32
        "name" => "Chekir"
        "email" => "cobrahan@bluewin.ch"
        "email_verified_at" => "2021-05-13 21:25:44"
        "password" => "$2y$10$Vd6F/aZkujCXYPmD9y0JbOBTSWRiixoB2MPwCjXV7XSUjPiajZ4.q"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => "FCjUTJYhPiy3uRflUURRnRRjeU7j5WskgpmO6xKVVC983klXvjJtEx8XNEbY"
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "user"
        "mollie_customer_id" => "cst_V9ms78sP68"
        "mollie_mandate_id" => "mdt_6k5r3subUG"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-05-13 21:22:58"
        "updated_at" => "2021-05-13 21:39:16"
      ]
      #original: array:22 [
        "id" => 32
        "name" => "Chekir"
        "email" => "cobrahan@bluewin.ch"
        "email_verified_at" => "2021-05-13 21:25:44"
        "password" => "$2y$10$Vd6F/aZkujCXYPmD9y0JbOBTSWRiixoB2MPwCjXV7XSUjPiajZ4.q"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => "FCjUTJYhPiy3uRflUURRnRRjeU7j5WskgpmO6xKVVC983klXvjJtEx8XNEbY"
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "user"
        "mollie_customer_id" => "cst_V9ms78sP68"
        "mollie_mandate_id" => "mdt_6k5r3subUG"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-05-13 21:22:58"
        "updated_at" => "2021-05-13 21:39:16"
      ]
      #changes: []
      #classCastCache: []
      #dates: []
      #dateFormat: null
      #dispatchesEvents: []
      #observables: []
      #relations: []
      #touches: []
      +timestamps: true
      #visible: []
      #guarded: array:1 [
        0 => "*"
      ]
      #rememberTokenName: "remember_token"
      #accessToken: null
    }
    3 => App\Models\User^ {#4641
      #fillable: array:8 [
        0 => "name"
        1 => "email"
        2 => "password"
        3 => "birthday"
        4 => "bio"
        5 => "gender"
        6 => "phone"
        7 => "role"
      ]
      #hidden: array:4 [
        0 => "password"
        1 => "remember_token"
        2 => "two_factor_recovery_codes"
        3 => "two_factor_secret"
      ]
      #casts: array:1 [
        "email_verified_at" => "datetime"
      ]
      #appends: array:1 [
        0 => "profile_photo_url"
      ]
      #connection: "mysql"
      #table: "users"
      #primaryKey: "id"
      #keyType: "int"
      +incrementing: true
      #with: []
      #withCount: []
      #perPage: 15
      +exists: true
      +wasRecentlyCreated: false
      #attributes: array:22 [
        "id" => 34
        "name" => "Nathalie"
        "email" => "nakendengue@hotmail.fr"
        "email_verified_at" => "2021-05-17 15:55:30"
        "password" => "$2y$10$DRnbdmpJfk6K0u2Z6Wcp1u/ln27o6BhtSFBzpRFAlJ/gUr8chBiLG"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => null
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "user"
        "mollie_customer_id" => "cst_qkvq9JNd2U"
        "mollie_mandate_id" => "mdt_WbTg3A6VSK"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-05-17 15:54:19"
        "updated_at" => "2021-05-17 15:57:48"
      ]
      #original: array:22 [
        "id" => 34
        "name" => "Nathalie"
        "email" => "nakendengue@hotmail.fr"
        "email_verified_at" => "2021-05-17 15:55:30"
        "password" => "$2y$10$DRnbdmpJfk6K0u2Z6Wcp1u/ln27o6BhtSFBzpRFAlJ/gUr8chBiLG"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => null
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "user"
        "mollie_customer_id" => "cst_qkvq9JNd2U"
        "mollie_mandate_id" => "mdt_WbTg3A6VSK"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-05-17 15:54:19"
        "updated_at" => "2021-05-17 15:57:48"
      ]
      #changes: []
      #classCastCache: []
      #dates: []
      #dateFormat: null
      #dispatchesEvents: []
      #observables: []
      #relations: []
      #touches: []
      +timestamps: true
      #visible: []
      #guarded: array:1 [
        0 => "*"
      ]
      #rememberTokenName: "remember_token"
      #accessToken: null
    }
    4 => null
    5 => null
    6 => App\Models\User^ {#4667
      #fillable: array:8 [
        0 => "name"
        1 => "email"
        2 => "password"
        3 => "birthday"
        4 => "bio"
        5 => "gender"
        6 => "phone"
        7 => "role"
      ]
      #hidden: array:4 [
        0 => "password"
        1 => "remember_token"
        2 => "two_factor_recovery_codes"
        3 => "two_factor_secret"
      ]
      #casts: array:1 [
        "email_verified_at" => "datetime"
      ]
      #appends: array:1 [
        0 => "profile_photo_url"
      ]
      #connection: "mysql"
      #table: "users"
      #primaryKey: "id"
      #keyType: "int"
      +incrementing: true
      #with: []
      #withCount: []
      #perPage: 15
      +exists: true
      +wasRecentlyCreated: false
      #attributes: array:22 [
        "id" => 26
        "name" => "Edgar Ochoa"
        "email" => "sitoc63035@dvdoto.com"
        "email_verified_at" => "2021-05-11 19:28:10"
        "password" => "$2y$10$P1EVvhrskvQ3BkuOsS6ptOubrZyxcOLIZVGKvN9e/jy1gfXVrpsV6"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => null
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "user"
        "mollie_customer_id" => "cst_3P9x3bpTK8"
        "mollie_mandate_id" => "mdt_F6UHb99u33"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-05-11 19:27:54"
        "updated_at" => "2021-06-16 10:44:04"
      ]
      #original: array:22 [
        "id" => 26
        "name" => "Edgar Ochoa"
        "email" => "sitoc63035@dvdoto.com"
        "email_verified_at" => "2021-05-11 19:28:10"
        "password" => "$2y$10$P1EVvhrskvQ3BkuOsS6ptOubrZyxcOLIZVGKvN9e/jy1gfXVrpsV6"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => null
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "user"
        "mollie_customer_id" => "cst_3P9x3bpTK8"
        "mollie_mandate_id" => "mdt_F6UHb99u33"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-05-11 19:27:54"
        "updated_at" => "2021-06-16 10:44:04"
      ]
      #changes: []
      #classCastCache: []
      #dates: []
      #dateFormat: null
      #dispatchesEvents: []
      #observables: []
      #relations: []
      #touches: []
      +timestamps: true
      #visible: []
      #guarded: array:1 [
        0 => "*"
      ]
      #rememberTokenName: "remember_token"
      #accessToken: null
    }
    7 => App\Models\User^ {#4669
      #fillable: array:8 [
        0 => "name"
        1 => "email"
        2 => "password"
        3 => "birthday"
        4 => "bio"
        5 => "gender"
        6 => "phone"
        7 => "role"
      ]
      #hidden: array:4 [
        0 => "password"
        1 => "remember_token"
        2 => "two_factor_recovery_codes"
        3 => "two_factor_secret"
      ]
      #casts: array:1 [
        "email_verified_at" => "datetime"
      ]
      #appends: array:1 [
        0 => "profile_photo_url"
      ]
      #connection: "mysql"
      #table: "users"
      #primaryKey: "id"
      #keyType: "int"
      +incrementing: true
      #with: []
      #withCount: []
      #perPage: 15
      +exists: true
      +wasRecentlyCreated: false
      #attributes: array:22 [
        "id" => 48
        "name" => "Ed test payment"
        "email" => "bacet65659@moxkid.com"
        "email_verified_at" => "2021-06-23 10:14:28"
        "password" => "$2y$10$AfLzee4W62QB0CVs7Z4sZ.UBQKvKg4DxxOyuacKlaZ53lwiZbVAZi"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => null
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "user"
        "mollie_customer_id" => "cst_PPF4zssje7"
        "mollie_mandate_id" => "mdt_hR34qdCa89"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-06-23 10:14:15"
        "updated_at" => "2021-06-23 10:15:50"
      ]
      #original: array:22 [
        "id" => 48
        "name" => "Ed test payment"
        "email" => "bacet65659@moxkid.com"
        "email_verified_at" => "2021-06-23 10:14:28"
        "password" => "$2y$10$AfLzee4W62QB0CVs7Z4sZ.UBQKvKg4DxxOyuacKlaZ53lwiZbVAZi"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => null
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "user"
        "mollie_customer_id" => "cst_PPF4zssje7"
        "mollie_mandate_id" => "mdt_hR34qdCa89"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-06-23 10:14:15"
        "updated_at" => "2021-06-23 10:15:50"
      ]
      #changes: []
      #classCastCache: []
      #dates: []
      #dateFormat: null
      #dispatchesEvents: []
      #observables: []
      #relations: []
      #touches: []
      +timestamps: true
      #visible: []
      #guarded: array:1 [
        0 => "*"
      ]
      #rememberTokenName: "remember_token"
      #accessToken: null
    }
    8 => App\Models\User^ {#4673
      #fillable: array:8 [
        0 => "name"
        1 => "email"
        2 => "password"
        3 => "birthday"
        4 => "bio"
        5 => "gender"
        6 => "phone"
        7 => "role"
      ]
      #hidden: array:4 [
        0 => "password"
        1 => "remember_token"
        2 => "two_factor_recovery_codes"
        3 => "two_factor_secret"
      ]
      #casts: array:1 [
        "email_verified_at" => "datetime"
      ]
      #appends: array:1 [
        0 => "profile_photo_url"
      ]
      #connection: "mysql"
      #table: "users"
      #primaryKey: "id"
      #keyType: "int"
      +incrementing: true
      #with: []
      #withCount: []
      #perPage: 15
      +exists: true
      +wasRecentlyCreated: false
      #attributes: array:22 [
        "id" => 50
        "name" => "Gabriel zambrano"
        "email" => "gabriel.zambrano@pm.me"
        "email_verified_at" => "2021-06-28 12:32:09"
        "password" => "$2y$10$fmSkNk52JKwZNlcTNoBdF.xxhLUR3y0Z8n2BmB4u0jz4jxS5tgpMi"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => null
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "user"
        "mollie_customer_id" => "cst_Rb4nNTCQba"
        "mollie_mandate_id" => "mdt_t6BTSNEs9N"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-06-28 12:31:34"
        "updated_at" => "2021-06-28 12:56:08"
      ]
      #original: array:22 [
        "id" => 50
        "name" => "Gabriel zambrano"
        "email" => "gabriel.zambrano@pm.me"
        "email_verified_at" => "2021-06-28 12:32:09"
        "password" => "$2y$10$fmSkNk52JKwZNlcTNoBdF.xxhLUR3y0Z8n2BmB4u0jz4jxS5tgpMi"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => null
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "user"
        "mollie_customer_id" => "cst_Rb4nNTCQba"
        "mollie_mandate_id" => "mdt_t6BTSNEs9N"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-06-28 12:31:34"
        "updated_at" => "2021-06-28 12:56:08"
      ]
      #changes: []
      #classCastCache: []
      #dates: []
      #dateFormat: null
      #dispatchesEvents: []
      #observables: []
      #relations: []
      #touches: []
      +timestamps: true
      #visible: []
      #guarded: array:1 [
        0 => "*"
      ]
      #rememberTokenName: "remember_token"
      #accessToken: null
    }
    9 => App\Models\User^ {#4675
      #fillable: array:8 [
        0 => "name"
        1 => "email"
        2 => "password"
        3 => "birthday"
        4 => "bio"
        5 => "gender"
        6 => "phone"
        7 => "role"
      ]
      #hidden: array:4 [
        0 => "password"
        1 => "remember_token"
        2 => "two_factor_recovery_codes"
        3 => "two_factor_secret"
      ]
      #casts: array:1 [
        "email_verified_at" => "datetime"
      ]
      #appends: array:1 [
        0 => "profile_photo_url"
      ]
      #connection: "mysql"
      #table: "users"
      #primaryKey: "id"
      #keyType: "int"
      +incrementing: true
      #with: []
      #withCount: []
      #perPage: 15
      +exists: true
      +wasRecentlyCreated: false
      #attributes: array:22 [
        "id" => 39
        "name" => "Kouamé Test"
        "email" => "marc.d.kouadio@gmail.com"
        "email_verified_at" => "2021-05-25 08:54:29"
        "password" => "$2y$10$X9ZnfRFxWgCds0OmbFEIuOXndn5usyWX.vBFlTK8Eb29ZPrnSGxzO"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => "pI3XXYnSogBVymnyhiwIkXwYmg2epFvWSRsPARsJUZtUz6myORJDrMUpgbng"
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "user"
        "mollie_customer_id" => "cst_8TCRzHrM8s"
        "mollie_mandate_id" => "mdt_7qzHVF48h2"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-05-25 08:51:57"
        "updated_at" => "2021-06-28 16:17:58"
      ]
      #original: array:22 [
        "id" => 39
        "name" => "Kouamé Test"
        "email" => "marc.d.kouadio@gmail.com"
        "email_verified_at" => "2021-05-25 08:54:29"
        "password" => "$2y$10$X9ZnfRFxWgCds0OmbFEIuOXndn5usyWX.vBFlTK8Eb29ZPrnSGxzO"
        "two_factor_secret" => null
        "two_factor_recovery_codes" => null
        "remember_token" => "pI3XXYnSogBVymnyhiwIkXwYmg2epFvWSRsPARsJUZtUz6myORJDrMUpgbng"
        "current_team_id" => null
        "profile_photo_path" => null
        "birthday" => null
        "bio" => null
        "gender" => null
        "phone" => null
        "role" => "user"
        "mollie_customer_id" => "cst_8TCRzHrM8s"
        "mollie_mandate_id" => "mdt_7qzHVF48h2"
        "tax_percentage" => "0.0000"
        "trial_ends_at" => null
        "extra_billing_information" => null
        "created_at" => "2021-05-25 08:51:57"
        "updated_at" => "2021-06-28 16:17:58"
      ]
      #changes: []
      #classCastCache: []
      #dates: []
      #dateFormat: null
      #dispatchesEvents: []
      #observables: []
      #relations: []
      #touches: []
      +timestamps: true
      #visible: []
      #guarded: array:1 [
        0 => "*"
      ]
      #rememberTokenName: "remember_token"
      #accessToken: null
    }
  ]
}`

**Comment by sandervanhooft** [comment] 2021-07-13 11:48
Deleted last post for sensitive content.

**Comment by sandervanhooft** [comment] 2021-07-14 13:13
So it appears some of your order items are not properly resolving their owners, returning `null` instead of a `User` model.

If you lookup the order_items table, what do you see in the `owner_x` columns?

**Comment by gabzon** [comment] 2021-07-15 11:26
I do notice that some fields in some rows are like this:
orderable_type = Null
orderable_id = Null
owner_type=App\Models\User
owner_id="the id" (sometimes this is repeated) 

Sometimes I also get
order_id=Null

Should I delete this lines, they appear at the beginning of the table?

**Comment by sandervanhooft** [comment] 2021-07-20 10:12
You can try that, if it's on production make sure to keep a backup somewhere.

**Comment by gabzon** [comment] 2021-07-20 12:15
I've just notice every time someone make an order the database creates 2 lines and one of this lines is has an order_id null. Is this a normal behaviour ?

<img width="1679" alt="Screenshot 2021-07-20 at 14 13 58" src="https://user-images.githubusercontent.com/142036/126321954-f4998fe8-32f3-4a63-a648-551c9d510a5b.png">

**Comment by sandervanhooft** [comment] 2021-07-20 12:44
Yes that's by design 👍

**Comment by sandervanhooft** [comment] 2021-07-26 14:31
Closing this for now, let me know if it should be reopened.

**Closed by sandervanhooft** 2021-07-26 14:31 UTC

**Comment by gabzon** [comment] 2021-07-29 14:16
Hi @sandervanhooft,
It is still not working unfortunately. 
I have configure the payments to happen daily, and nothing is being executed unfortunately. 

I run cashier:run manually and it said "created 0 orders"

I run the command you told me and I get this: 

<img width="620" alt="Screenshot 2021-07-29 at 16 14 02" src="https://user-images.githubusercontent.com/142036/127507928-f0f5ddca-f83b-4e97-ae93-c3294fddc6b1.png">

I have open the project here: https://github.com/gabzon/onlinedance

**Comment by sandervanhooft** [comment] 2021-08-05 12:27
Hi @gabzon,

We've installed your project and ran it. We cannot reproduce the issue, everything seems to be working fine.
