### ISSUE TITLE
Adding trial days will not store subscriptions

### ISSUE THREAD

**Issue by stefano-cortese** [laravel/cashier-mollie#264] opened 2020-10-15 21:45 UTC
Hi, 

we found a problem with the trial period. 

We create the subscription checkout URL with this code:
```
user()->newSubscription(self::MOLLIE_PRODUCT, $request->plan)->trialDays(14)->create();
```
The library creates the URL correctly and the payment works.

The problem is on collecting subscriptions from the first payment webhook URL.
We cannot store the subscription and we have this error in our Laravel logs:

```
Creating an order requires items to have a single owner  
/vendor/laravel/cashier-mollie/src/Order/Order.php:74
```

This error occurs only when we set the trial days, without trial days all the flow works well. 
The owners count is 2 and this is the `items` content:
```
[
  {
    "owner_type": "Platform\\Users\\Models\\User",
    "owner_id": 200,
    "process_at": "2020-10-15T18:37:25.000000Z",
    "description": "6 months payment",
    "currency": "EUR",
    "unit_price": "0",
    "tax_percentage": 0,
    "quantity": 1,
    "orderable_id": 147,
    "orderable_type": "Laravel\\Cashier\\Subscription",
    "updated_at": "2020-10-15T18:37:25.000000Z",
    "created_at": "2020-10-15T18:37:25.000000Z",
    "id": 413
  },
  {
    "description": "Description",
    "currency": "EUR",
    "process_at": "2020-10-15T18:37:25.000000Z",
    "unit_price": "100",
    "tax_percentage": 0,
    "quantity": 1,
    "owner_id": 200,
    "owner_type": "users",
    "updated_at": "2020-10-15T18:37:25.000000Z",
    "created_at": "2020-10-15T18:37:25.000000Z",
    "id": 414
  }
]
```

Is it our configuration problem or is it a library problem?
Do you need other types of information?

Thanks in advance and many compliments for the great work!

**Comment by sandervanhooft** [comment] 2020-10-16 10:11
Hi @stefano-cortese !

Can you share the metadata that was stored on the first payment? It is accessible through Mollie's dashboard.

**Comment by stefano-cortese** [comment] 2020-10-16 12:06
Hi @sandervanhooft !

Thanks for the quick response!

These are the metadata:
```
{
  "owner": {
    "type": "Platform\\Users\\Models\\User",
    "id": 200
  },
  "actions": [
    {
      "handler": "Laravel\\Cashier\\FirstPayment\\Actions\\StartSubscription",
      "description": "6 months payment",
      "subtotal": {
        "currency": "EUR",
        "value": "0.00"
      },
      "plan": "plan_name",
      "name": "name",
      "quantity": 1,
      "trialUntil": "2020-10-29T19:12:50+00:00"
    },
    {
      "handler": "Laravel\\Cashier\\FirstPayment\\Actions\\AddGenericOrderItem",
      "description": "Description",
      "subtotal": {
        "currency": "EUR",
        "value": "1.00"
      },
      "taxPercentage": 0
    }
  ]
}
```

**Comment by cybernetix-belgrade** [comment] 2020-10-18 09:17
Seems to be /vendor/laravel/cashier-mollie/src/Order/Order.php:**73** should read:
if($items->owners()->unique('id')->count() > 1) {

**Comment by stefano-cortese** [comment] 2020-10-20 16:08
@sandervanhooft is @cybernetix-belgrade's response the solution for this problem or it could break the library?

**Comment by sandervanhooft** [comment] 2020-10-28 11:50
The PR itself looks good to me, not sure if it fixes your problem.

**Comment by sandervanhooft** [comment] 2020-10-28 11:51
The PR is now merged into `develop`, @stefano-cortese can you check if it fixes this issue?

**Comment by sandervanhooft** [comment] 2020-10-28 11:53
Wait, that was a bit too quick on my part.

The issue is the difference in owner types. The FQN vs `users`. Any clue where that is coming from?

**Comment by sandervanhooft** [comment] 2020-10-28 11:55
I mean this difference in your metadata:

```
"owner_type": "Platform\\Users\\Models\\User",

vs

"owner_type": "users",
```

The `users` is wrong.

**Comment by stefano-cortese** [comment] 2020-10-28 20:44
@sandervanhooft we created a new Laravel project in order to check if the problem is in the library or in our project.

In the new project, the trial works well so the problem is in our project. 

We will investigate it and we will share the solution to this issue for helping others devs.

**Comment by sandervanhooft** [comment] 2020-10-28 20:46
Thanks for that! I was wondering if the difference could be caused by a customized MorphMap in your app. That would make most sense to me from what I can see from here.

**Comment by stefano-cortese** [comment] 2020-10-28 20:49
Yes, we think that our customized MorphMap causes the problem!
Thanks @sandervanhooft for the support!

**Closed** 2020-12-14 11:52 UTC
