### ISSUE TITLE
Error when running Schedule or cashier:run

### ISSUE THREAD

**Issue by Pieterc2** [laravel/cashier-mollie#187] opened 2020-04-09 09:19 UTC
Okay so i was checking subscriptions earlier and found out that subscriptions weren't renewed. So i manually runned  cashier:run and this is what i get 
![image](https://user-images.githubusercontent.com/25752853/78879204-dd2fe800-7a53-11ea-88a2-3ed03eb35e4f.png)

So im confused how this happend. Thats why im here asking if anybody experienced this aswell and maybe has a solution for it :)

**Comment by sandervanhooft** [comment] 2020-04-09 09:28
Is there anything that could have broken the relationship between the OrderItem and Billable models in your app? Think overrides, non-default migrations, etc..

**Comment by tobischulz** [comment] 2020-05-18 13:29
Hello, i  have got that same problem. Turns out that the $this->owners() returned collection has NULL inside. Don´t know why but it could be fixed to break all other subscriptions/payments that has to be run by removing all NULL entries from the collection:

So in the OrderItemCollection:
![OrderItemCollectionHasNull](https://user-images.githubusercontent.com/576014/82218352-1180a900-991c-11ea-87bc-1e15b88e3072.png)

Reject all items that are NULL:
![OrderItemCollectionRejectNull](https://user-images.githubusercontent.com/576014/82218367-16455d00-991c-11ea-90ef-f19726dca6ef.png)

This would help that every other existing order will be executed. But it should be much better to find out why there are some NULL items in the owner collection.

**Comment by sandervanhooft** [comment] 2020-06-11 13:35
I agree that it's better to find out why null is being returned for some owners. Both the `owner_id` and `owner_type` table fields are mandatory, so I'm not sure what's causing this.

Can you share the database rows for the records that trigger this exception?

(Note that in your second code sample, the last two `$item`s are actually `$owner`s.)

**Comment by tobischulz** [comment] 2020-06-12 08:44
For me this occurred only on development till now. So i guess this might be happen when an `owner` gets deleted but `order_times` / `orders` still exist. 

Don´t know how to handle that right, cause if this would happen on production, no other order will be executed until this gets recognized by developer and get fixed by removing the `order_times`.

If you asked me it would be great if all order_items get processed and maybe an error log will be written or an event gets fired that there are order_items cant handled cause by missing owner. So the product does not get restricted by not paid subscriptions for customers.

Maybe this would not occur often, but when it does, some developers have to figure out whats wrong which can be frustrating on production.

**Comment by sandervanhooft** [comment] 2020-06-12 08:51
> If you asked me it would be great if all order_items get processed and maybe an error log will be written or an event gets fired that there are order_items cant handled cause by missing owner.

How about moving these to an `unprocessable_order_items` table, along with a `failure_reason` column? Another way could be by spawning a job for processing each order item collection. This would give us a log / failed jobs table for free.

> So the product does not get restricted by not paid subscriptions for customers.

When would this be a good idea? Can you elaborate on this use case?

**Comment by tobischulz** [comment] 2020-06-12 09:07
`How about moving these to an unprocessable_order_items table, along with a failure_reason column? Another way could be by spawning a job for processing each order item collection. This would give us a log / failed jobs table for free.`

That sounds nice! Love the job version. Would be great too for Horizon users.

`When would this be a good idea? Can you elaborate on this use case?`

I mean, if there are new payments not get handled, the subscription cycle_ends date was hit, the product is not available for customers anymore. This would happen if new order_items cant processed, caused by an order_item that has no owner. All order_items newer the owner-less oder-item will never get processed.

This could lead to "expired" subscriptions if the cashier:run error will not get recognized by the developer for days.

Not a thing that will happen often, but maybe it could.

**Comment by sandervanhooft** [comment] 2020-06-12 09:13
The subscription only ends when the `cancelled_at` is filled. This only happens when it's cancelled manually, or if the payment fails. Not if the order processing fails.

**Comment by sandervanhooft** [comment] 2020-06-12 09:14
> That sounds nice! Love the job version. Would be great too for Horizon users.

👍

**Comment by tobischulz** [comment] 2020-06-12 09:17
`The subscription only ends when the cancelled_at is filled. This only happens when it's cancelled manually, or if the payment fails. Not if the order processing fails.`

Oh okay, so the `subscription.cycle_ends_at` does not affect the active subscription state? So then there is no problem for customers, as they can user the subscribed service even the next payment does not has been processed.

**Comment by sandervanhooft** [comment] 2020-06-12 09:20
Exactly. But it's important this does not halt things, and the developer / merchant should be informed

**Comment by johnnyhertogs2** [comment] 2021-01-21 09:59
This happens to me, when I delete a billable object via Eloquent. The related subscription and order from the database are not cancelled or deleted, and that triggers the error. Is there an option to cancel all subscription for a billable object ON DELETE?

**Comment by sandervanhooft** [comment] 2021-01-21 10:22
> This happens to me, when I delete a billable object via Eloquent. The related subscription and order from the database are not cancelled or deleted, and that triggers the error. Is there an option to cancel all subscription for a billable object ON DELETE?

That's another issue. Best to cancel the subscriptions before deleting the user.

**Closed by sandervanhooft** 2021-01-21 10:22 UTC
