### ISSUE TITLE
Is is possible to add quantity to newSubscriptionViaMollieCheckout?

### ISSUE THREAD

**Issue by Pieterc2** [laravel/cashier-mollie#159] opened 2020-02-27 07:54 UTC
Currently i have a subscription system in place. A customer can get a subscription then will be redirected to the payment screen. And as soon as the payment is succesful it will start the subscription etc. But currently im trying to figure out how to add quantity to the first payment. For example buying 10 for 100$/mo subscriptions at the same and for the first time instead of 1/ 10$m.
Does anyone have a solution for this! would be great :)

**Comment by Pieterc2** [comment] 2020-02-27 07:57
Fixed it by doing this: $customer->newSubscriptionViaMollieCheckout($plan->name, $plan->slug)->quantity(3)->createUrl()

**Comment by Pieterc2** [comment] 2020-02-27 08:05
Okay i fixed the quanitity part. If i go to the checkout the price increases. But in the database it still registers as 1 subscription
also when i get $event->order; in FirstPaymentPaid for example it is also 1 subscription with the price of 1 subscription.
also the order is price of 1 subscription
![image](https://user-images.githubusercontent.com/25752853/75423936-0c751480-5940-11ea-982d-1df3c121d30c.png)

also the order item is like this:
![image](https://user-images.githubusercontent.com/25752853/75423999-2b73a680-5940-11ea-8dd5-a90c304d9394.png)
The quanitity is still 1 and the price is still as 1 subscription.

**Comment by sandervanhooft** [comment] 2020-02-27 08:13
Hi @Pieterc2, can you dump the metada from the Mollie payment here? You can grab it at Mollie’s dashboard.

**Comment by Pieterc2** [comment] 2020-02-27 09:41
{
  "owner": {
    "type": "App\\Customer",
    "id": 317
  },
  "actions": [
    {
      "handler": "Laravel\\Cashier\\FirstPayment\\Actions\\StartSubscription",
      "description": "Steppi Subscription",
      "subtotal": {
        "currency": "EUR",
        "value": "104.97"
      },
      "plan": "steppi",
      "name": "Steppi",
      "quantity": 3
    }
  ],
  "shippingAddress": {
    "delivery_address": "test43",
    "delivery_city": "test",
    "delivery_postal_code": "6005RH",
    "delivery_country_code": "BE"
  }
}

**Comment by sandervanhooft** [comment] 2020-02-27 10:24
Thanks. What version of cashier-mollie are you running?

**Comment by Pieterc2** [comment] 2020-02-27 10:31
![image](https://user-images.githubusercontent.com/25752853/75436340-ae066100-5954-11ea-9140-9640a515f765.png)

**Comment by sandervanhooft** [comment] 2020-02-27 10:53
Thanks. I think I have found the cause.

**Comment by sandervanhooft** [comment] 2020-02-27 11:05
A fix is now merged in the `develop` branch. @Pieterc2 Can you confirm this solves the issue?

**Comment by Pieterc2** [comment] 2020-02-27 11:52
Ok so i did a test order of 34.99 x 3 should be around 100 euro's of an order
![image](https://user-images.githubusercontent.com/25752853/75442426-bdd77280-595f-11ea-9129-
95030e529dd1.png)

Its 3x the amount of the order in the table orders it should be around 100 
![image](https://user-images.githubusercontent.com/25752853/75442456-cf207f00-595f-11ea-987b-9cb479cda516.png)

While in the order_item tabel it it registered succesfully as 3 items and the unit price is correct
![image](https://user-images.githubusercontent.com/25752853/75442478-dcd60480-595f-11ea-86d6-5dbf44d0da7d.png)

**Comment by sandervanhooft** [comment] 2020-02-27 12:58
Ok, so to sum up:

- subscription record now has correct quantity
- The scheduled OrderItem (257) has the correct quantity and price.
- The first payment amount is correct.
- The processed OrderItem (258) has stored the correct quantity (3), but also has the quantity applied to the unit price (now 104.97, which is wrong).
- This results in the Order calculating a total of 3 x 104.97 = 314.91 . This calculation is correct, but the input is wrong due to the OrderItem issue above.

Can you confirm this?

**Comment by Pieterc2** [comment] 2020-02-27 13:00
Yes this is correct. 

Do you also know the reason why it makes 2 entry's in the order table?
![image](https://user-images.githubusercontent.com/25752853/75447359-8077e280-5969-11ea-9913-63dc284859ff.png)
1 with no order_id and 1 with order_id. Just a quick question between :)

**Comment by sandervanhooft** [comment] 2020-02-27 13:10
Ok, working on a fix.

**Comment by sandervanhooft** [comment] 2020-02-27 13:21
It's now on `develop`, can you give it a whirl?

**Comment by Pieterc2** [comment] 2020-02-27 13:53
Everything seems to be working now this is great!
![image](https://user-images.githubusercontent.com/25752853/75450808-c2a42280-596f-11ea-89a8-8392b80262ec.png)
![image](https://user-images.githubusercontent.com/25752853/75450836-cf287b00-596f-11ea-8f37-a4c58215cd97.png)
![image](https://user-images.githubusercontent.com/25752853/75450872-dfd8f100-596f-11ea-9ab8-1a255198dd4e.png)

One more quick question:
As of incrementQuantitys. When i for example now do an  ->incrementQuantity(10) on the same plan they group up in one subscription. Is this only when its on the same day because the payment gets collected the next day. Maybe im not understanding this party fully can you maybe explain the logic behind this :)?
![image](https://user-images.githubusercontent.com/25752853/75451326-aa80d300-5970-11ea-97eb-306b56132206.png)

![image](https://user-images.githubusercontent.com/25752853/75451403-cab09200-5970-11ea-8a8e-1df58e57970c.png)

**Comment by sandervanhooft** [comment] 2020-02-27 14:02
Great!

Modifications on running subscriptions like swapping and changing the quantity essentially apply the changes and reset the billing cycle. The amount overpaid (time left on old subscription settings) is reimbursed.

Check out the Subscription's `updateQuantity` and (especially) `restartCycleWithModifications` methods if you want to take a look under the hood.

**Closed by sandervanhooft** 2020-02-27 14:02 UTC
